import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from "react-hot-toast";

const cairo = localFont({
  src: [
    {
      path: "../public/fonts/Cairo-ExtraLight.ttf",
      weight: "200",
    },
    {
      path: "../public/fonts/Cairo-Light.ttf",
      weight: "300",
    },
    {
      path: "../public/fonts/Cairo-Regular.ttf",
      weight: "400",
    },
    {
      path: "../public/fonts/Cairo-Medium.ttf",
      weight: "500",
    },
    {
      path: "../public/fonts/Cairo-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "../public/fonts/Cairo-Bold.ttf",
      weight: "700",
    },
    {
      path: "../public/fonts/Cairo-ExtraBold.ttf",
      weight: "800",
    },
    {
      path: "../public/fonts/Cairo-Black.ttf",
      weight: "900",
    },
    {
      path: "../public/fonts/Cairo-VariableFont_slnt,wght.ttf",
      weight: "100 900", // Variable weight range
    },
  ],
  variable: "--font-cairo",
});

export const metadata: Metadata = {
  title: "FMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${cairo.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <ThemeProvider
          attribute={"class"}
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
